name: orbit-dataset
channels:
  - pytorch
  - plotly
dependencies:
  - python=3.7
  - pip=20.0.2=py37_3
  - plotly=4.8.1=py_0
  - pytorch=1.8.1
  - torchvision=0.9.1
  - pip:
    - thop==0.0.31-2005241907
